<?php
App::uses('AppModel', 'Model');                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                             
    class StudyAuditor extends AppModel {                                                                                                                                                                                                                    
        public $actsAs = array('Containable', 'Search.Searchable');                                                                                                                                                                                          
                                                                                                                                                                                                                                                             
        public $filterArgs = array(                                                                                                                                                                                                                          
            'protocol_no' => array('type' => 'like', 'encode' => true),                                                                                                                                                                                      
        );                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                             
        public $belongsTo = array(                                                                                                                                                                                                                           
            'User' => array(                                                                                                                                                                                                                                 
                'className' => 'User',                                                                                                                                                                                                                       
                'foreignKey' => 'user_id',                                                                                                                                                                                                                   
            ),                                                                                                                                                                                                                                               
            'Application' => array(                                                                                                                                                                                                                          
                'className' => 'Application',                                                                                                                                                                                                                
                'foreignKey' => 'application_id',                                                                                                                                                                                                            
            )                                                                                                                                                                                                                                                
        );                                                                                                                                                                                                                                                   
    }