services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "9180:80"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: hatua.
      DB_NAME: ctr
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DATABASE: "0"
      REDIS_NAMESPACE: resque
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7.42
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: hatua.
      MYSQL_DATABASE: ctr
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ctr.sql:/docker-entrypoint-initdb.d/ctr.sql:ro

  phpmyadmin:
    image: phpmyadmin:5
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: hatua.
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    platform: linux/amd64

volumes:
  db_data: