[supervisord]
nodaemon=true

[program:apache]
command=/usr/sbin/apachectl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/apache.log
stderr_logfile=/var/log/apache.err.log
 
[program:cakeresque]
command=/var/www/html/app/Console/cake CakeResque.CakeResque start --queue=*
directory=/var/www/html
autostart=true
autorestart=true
startretries=10
stdout_logfile=/var/log/cakeresque.log
stderr_logfile=/var/log/cakeresque.err.log