  <?php                                                                                                                                                                                                                                                                                                                         
    App::uses('AppController', 'Controller');                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                  
    class AuditReportsController extends AppController {                                                                                                                                                                                                                                                                          
        public $uses = array('AuditReport', 'AuditChecklist', 'Application', 'StudyAuditor', 'User', 'AuditTrail');                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                  
        public function beforeFilter() {                                                                                                                                                                                                                                                                                          
            parent::beforeFilter();                                                                                                                                                                                                                                                                                               
            if (isset($this->Auth)) {                                                                                                                                                                                                                                                                                             
                $this->Auth->allow('auditor_edit');                                                                                                                                                                                                                                                                               
            }                                                                                                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                  
        public function auditor_edit($id = null, $application_id = null) {                                                                                                                                                                                                                                                        
            if (!$application_id) {                                                                                                                                                                                                                                                                                               
                $application_id = $id;                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                  
            $user_id = $this->Auth->User('id');                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                  
            if ($this->request->is('post') || $this->request->is('put')) {                                                                                                                                                                                                                                                        
                $reportData = $this->request->data;                                                                                                                                                                                                                                                                               
                if (empty($reportData['AuditReport']['application_id'])) {                                                                                                                                                                                                                                                        
                    $reportData['AuditReport']['application_id'] = $application_id;                                                                                                                                                                                                                                               
                }                                                                                                                                                                                                                                                                                                                 
                $reportData['AuditReport']['user_id'] = $user_id;                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                  
                // --- WHEN AUDITOR SUBMITS OFFICIAL REPORT ---                                                                                                                                                                                                                                                                   
                if (isset($this->request->data['submit_report'])) {                                                                                                                                                                                                                                                               
                    $reportData['AuditReport']['submitted'] = 1;                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                  
                    // 1. Record Submission in Audit Trail                                                                                                                                                                                                                                                                        
                    $application = $this->Application->findById($application_id);                                                                                                                                                                                                                                                 
                    $this->AuditTrail->create();                                                                                                                                                                                                                                                                                  
                    $this->AuditTrail->save(array(                                                                                                                                                                                                                                                                                
                        'AuditTrail' => array(                                                                                                                                                                                                                                                                                    
                            'foreign_key' => $application_id,                                                                                                                                                                                                                                                                     
                            'model'       => 'AuditReport',                                                                                                                                                                                                                                                                       
                            'message'     => 'Official Audit Report for Protocol ' . $application['Application']['protocol_no'] . ' submitted by Auditor ' . $this->Auth->User('name') . ' with outcome: ' . $reportData['AuditReport']['outcome'],                                                                               
                            'ip'          => $this->request->clientIp()                                                                                                                                                                                                                                                           
                        )                                                                                                                                                                                                                                                                                                         
                    ));                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                  
                    // 2. Email Notification to All Managers (Group ID = 2)                                                                                                                                                                                                                                                       
                    $managers = $this->User->find('all', array(                                                                                                                                                                                                                                                                   
                        'conditions' => array('User.group_id' => 2, 'User.is_active' => 1)                                                                                                                                                                                                                                        
                    ));                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                  
                    foreach ($managers as $mgr) {                                                                                                                                                                                                                                                                                 
                        $emailData = array(                                                                                                                                                                                                                                                                                       
                            'email'   => $mgr['User']['email'],                                                                                                                                                                                                                                                                   
                            'subject' => 'New Audit Report Awaiting Review - ' . $application['Application']['protocol_no'],                                                                                                                                                                                                      
                            'message' => '<p>Dear ' . h($mgr['User']['name']) . ',</p>' .                                                                                                                                                                                                                                         
                                         '<p>A new Audit Report has been submitted and is awaiting your review.</p>' .                                                                                                                                                                                                            
                                         '<ul>' .                                                                                                                                                                                                                                                                                 
                                           '<li><strong>Protocol Number:</strong> ' . h($application['Application']['protocol_no']) . '</li>' .                                                                                                                                                                                   
                                           '<li><strong>Protocol Title:</strong> ' . h($application['Application']['study_title']) . '</li>' .                                                                                                                                                                                    
                                           '<li><strong>Auditor Name:</strong> ' . h($this->Auth->User('name')) . '</li>' .                                                                                                                                                                                                       
                                           '<li><strong>Audit Outcome:</strong> ' . h($reportData['AuditReport']['outcome']) . '</li>' .                                                                                                                                                                                          
                                           '<li><strong>Submission Date:</strong> ' . date('d-M-Y H:i') . '</li>' .                                                                                                                                                                                                               
                                         '</ul>' .                                                                                                                                                                                                                                                                                
                                         '<p>Log in to the Manager Dashboard to review the report.</p>'                                                                                                                                                                                                                           
                        );                                                                                                                                                                                                                                                                                                        
                        CakeResque::enqueue('default', 'GenericEmailShell', array('sendEmail', $emailData));                                                                                                                                                                                                                      
                    }                                                                                                                                                                                                                                                                                                             
                }                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                  
                if ($this->AuditReport->saveAssociated($reportData, array('deep' => true))) {                                                                                                                                                                                                                                     
                    $this->Session->setFlash(__('Audit Report processed successfully.'), 'alerts/flash_success');                                                                                                                                                                                                                 
                    return $this->redirect(array('controller' => 'applications', 'action' => 'view', $application_id, 'auditor' => true));                                                                                                                                                                                        
                }                                                                                                                                                                                                                                                                                                                 
            }                                                                                                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                                                                                         
    }                             