 <?php                                                                                                                                                                                                                                                                                                                         
    App::uses('AppController', 'Controller');                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                  
    class StudyAuditorsController extends AppController {                                                                                                                                                                                                                                                                         
        public $uses = array('StudyAuditor', 'Application', 'User', 'AuditTrail');                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                  
        /**                                                                                                                                                                                                                                                                                                                       
         * Manager Assigns Auditor to Protocol                                                                                                                                                                                                                                                                                    
         */                                                                                                                                                                                                                                                                                                                       
        public function manager_assign($application_id = null) {                                                                                                                                                                                                                                                                  
            if ($this->request->is('post')) {                                                                                                                                                                                                                                                                                     
                $auditor_id = $this->request->data['StudyAuditor']['user_id'];                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                  
                $data = array(                                                                                                                                                                                                                                                                                                    
                    'StudyAuditor' => array(                                                                                                                                                                                                                                                                                      
                        'application_id' => $application_id,                                                                                                                                                                                                                                                                      
                        'user_id'        => $auditor_id                                                                                                                                                                                                                                                                           
                    )                                                                                                                                                                                                                                                                                                             
                );                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                  
                $this->StudyAuditor->create();                                                                                                                                                                                                                                                                                    
                if ($this->StudyAuditor->save($data)) {                                                                                                                                                                                                                                                                           
                    $application = $this->Application->findById($application_id);                                                                                                                                                                                                                                                 
                    $auditor     = $this->User->findById($auditor_id);                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                  
                    // 1. Record Assignment in Audit Trail                                                                                                                                                                                                                                                                        
                    $this->AuditTrail->create();                                                                                                                                                                                                                                                                                  
                    $this->AuditTrail->save(array(                                                                                                                                                                                                                                                                                
                        'AuditTrail' => array(                                                                                                                                                                                                                                                                                    
                            'foreign_key' => $application_id,                                                                                                                                                                                                                                                                     
                            'model'       => 'StudyAuditor',                                                                                                                                                                                                                                                                      
                            'message'     => 'Protocol ' . $application['Application']['protocol_no'] . ' (' . $application['Application']['study_title'] . ') assigned to Auditor ' . $auditor['User']['name'] . ' by Manager ' . $this->Auth->User('name'),                                                                     
                            'ip'          => $this->request->clientIp()                                                                                                                                                                                                                                                           
                        )                                                                                                                                                                                                                                                                                                         
                    ));                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                  
                    // 2. Email Notification to Assigned Auditor                                                                                                                                                                                                                                                                  
                    $emailData = array(                                                                                                                                                                                                                                                                                           
                        'email'   => $auditor['User']['email'],                                                                                                                                                                                                                                                                   
                        'subject' => 'Protocol Assignment Notification - ' . $application['Application']['protocol_no'],                                                                                                                                                                                                          
                        'message' => '<p>Dear ' . h($auditor['User']['name']) . ',</p>' .                                                                                                                                                                                                                                         
                                     '<p>You have been assigned to audit Protocol: <strong>' . h($application['Application']['protocol_no']) . '</strong> (' . h($application['Application']['study_title']) . ').</p>' .                                                                                                         
                                     '<p>Assignment Date: ' . date('d-M-Y H:i') . '</p>' .                                                                                                                                                                                                                                        
                                     '<p>The protocol is now available for your review in the Auditor Dashboard.</p>'                                                                                                                                                                                                             
                    );                                                                                                                                                                                                                                                                                                            
                    CakeResque::enqueue('default', 'GenericEmailShell', array('sendEmail', $emailData));                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                  
                    $this->Session->setFlash(__('Auditor assigned successfully.'), 'alerts/flash_success');                                                                                                                                                                                                                       
                }                                                                                                                                                                                                                                                                                                                 
            }                                                                                                                                                                                                                                                                                                                     
            return $this->redirect(array('controller' => 'applications', 'action' => 'view', $application_id));                                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                  
        /**                                                                                                                                                                                                                                                                                                                       
         * Manager Revokes Auditor Assignment from Protocol                                                                                                                                                                                                                                                                       
         */                                                                                                                                                                                                                                                                                                                       
        public function manager_revoke($id = null, $application_id = null) {                                                                                                                                                                                                                                                      
            $assignment = $this->StudyAuditor->find('first', array(                                                                                                                                                                                                                                                               
                'conditions' => array('StudyAuditor.id' => $id),                                                                                                                                                                                                                                                                  
                'contain'    => array('User', 'Application')                                                                                                                                                                                                                                                                      
            ));                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                  
            if ($this->StudyAuditor->delete($id)) {                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                  
                // Record Revocation in Audit Trail                                                                                                                                                                                                                                                                               
                $this->AuditTrail->create();                                                                                                                                                                                                                                                                                      
                $this->AuditTrail->save(array(                                                                                                                                                                                                                                                                                    
                    'AuditTrail' => array(                                                                                                                                                                                                                                                                                        
                        'foreign_key' => $application_id,                                                                                                                                                                                                                                                                         
                        'model'       => 'StudyAuditor',
                        'message'     => 'Assignment of Protocol ' . $assignment['Application']['protocol_no'] . ' revoked from Auditor ' . $assignment['User']['name'] . ' by Manager ' . $this->Auth->User('name'),
                        'ip'          => $this->request->clientIp()
                    )
                ));
  
                $this->Session->setFlash(__('Auditor assignment revoked.'), 'alerts/flash_success');
            }
            return $this->redirect(array('controller' => 'applications', 'action' => 'view', $application_id));
        }
    }